package crd

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordSecret) DeepCopyInto(out *PasswordSecret) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordSecret.
func (in *PasswordSecret) DeepCopy() *PasswordSecret {
	if in == nil {
		return nil
	}
	out := new(PasswordSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RDSDatabase) DeepCopyInto(out *RDSDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RDSDatabase.
func (in *RDSDatabase) DeepCopy() *RDSDatabase {
	if in == nil {
		return nil
	}
	out := new(RDSDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RDSDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RDSDatabaseList) DeepCopyInto(out *RDSDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RDSDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RDSDatabaseList.
func (in *RDSDatabaseList) DeepCopy() *RDSDatabaseList {
	if in == nil {
		return nil
	}
	out := new(RDSDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RDSDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RDSDatabaseSpec) DeepCopyInto(out *RDSDatabaseSpec) {
	*out = *in
	out.Password = in.Password
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RDSDatabaseSpec.
func (in *RDSDatabaseSpec) DeepCopy() *RDSDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(RDSDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RDSDatabaseStatus) DeepCopyInto(out *RDSDatabaseStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RDSDatabaseStatus.
func (in *RDSDatabaseStatus) DeepCopy() *RDSDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(RDSDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}
