
[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  version = "v2.0.0-preview.4"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "k8s.io/api"

[[constraint]]
  branch = "master"
  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"
