apiVersion: v1
kind: Secret
metadata:
  name: REPLACE_OPERATOR_NAME
  namespace: default
type: Opaque
data:
  AWS_ACCESS_KEY_ID: changeme!!!
  AWS_SECRET_ACCESS_KEY: changeme!!!
  AWS_REGION: changeme!!! #us-east-2
