apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.aws.pmacik.dev
spec:
  group: aws.pmacik.dev
  names:
    kind: Database
    listKind: DatabaseList
    singular: database
    plural: databases
    shortNames:
      - rds
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description:
            "APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
          type: string
        kind:
          description:
            "Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
          type: string
        metadata:
          type: object
        spec:
          properties:
            backupRetentionPeriod:
              format: int64
              type: integer
            class:
              description: '"postgres"'
              type: string
            dbName:
              type: string
            deleteProtection:
              description: between 0 and 35, zero means disable
              type: boolean
            engine:
              type: string
            iops:
              format: int64
              type: integer
            multiAZ:
              description: size in gb
              type: boolean
            password:
              properties:
                key:
                  type: string
                name:
                  type: string
              required:
                - name
                - key
              type: object
            publiclyAccessible:
              type: boolean
            size:
              description: like "db.t2.micro"
              format: int64
              type: integer
            storageEncrypted:
              type: boolean
            storageType:
              type: string
            username:
              type: string
          required:
            - username
            - password
            - dbName
            - engine
            - class
            - size
          type: object
        status:
          #          required:
          #          - dbConnectionConfig
          #          - dbCredentials
          type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
