apiVersion: v1
kind: Secret
metadata:
  name: REPLACE_OPERATOR_NAME
  namespace: openshift-operators
type: Opaque
data:
  AWS_ACCESS_KEY_ID: REPLACE_AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: REPLACE_AWS_SECRET_ACCESS_KEY
  AWS_REGION: dXMtZWFzdC0y #(BASE64:us-east-2)
